# Base configs
#baseurl: "https://photography.rampatra.com"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sai Saketh Cherukuri"
subtitle: "See the world through my eyes!"
author: "Sai Saketh Cherukuri"
header:
 title: "Photography"
 subtitle: "by Sai Saketh"
footer:
 name: "Hey there, my name is Saketh!"
 bio: "I am an final year MSc.Mathematics student at the Sri Sathya Sai Institute of Higher Learning, India. I am a passionate photographer and love to capture the beauty of nature."
 # Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  linkedin: "https://www.linkedin.com/in/sai-saketh-cherukuri-825456250/"
  github: "https://github.com/ssaketh-ch"
